config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'questions#index'

  get 'login' => "admin#index", as: "login"
  post 'login' => "admin#create"
  get 'logout' => "admin#destroy", as: "logout"

  resources :questions, path: '', shallow: true do
    resources :answers, except: [:index, :show]
  end

  resources :instructions, except: [:new, :create]

  get ':id/:answer_id/empty' => "questions#empty", as: "empty"
  get 'new/:answer_id' => "questions#new", as: "new_fat_question"
  post 'fat/:answer_id' => "questions#create", as: 'question_answer'
  get 'new/int/:answer_id' => "instructions#new", as: "new_instruction"
  post 'int/:answer_id' => "instructions#create", as: 'instruction_answer'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :children, polymorphic: true, dependent: :destroy

  validates :title, presence: true,
            length: { maximum: 200 }
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  has_one :answer, as: :children, dependent: :destroy

  validates :title, presence: true,
            length: { minimum: 1, maximum: 150 }

  validates :text, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  has_one :answer, as: :children
  validates :title, presence: true,
            length: { minimum: 1, maximum: 200 }

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index

  end
  def create
    @adminname = params.require(:admin).permit(:login)[:login]
    @adminpass = params.require(:admin).permit(:password)[:password]
    @admin = Admin.find_by(login: @adminname, password: @adminpass)
    if  @admin
      session[:admin] = true
      flash[:notice] = "Вы авторизировались"
      redirect_to root_path
    else
      flash[:notice] = "Неверный логин или пароль"
      redirect_to login_path
    end
  end
  def destroy
    reset_session
    flash[:notice] = "Вы вышли из системы"
    redirect_to login_path
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:edit, :update, :destroy]
  before_action :set_question, only: [:new, :create]
  before_action :authorize, except: [:index]
  def index
    @answer = Answer.first
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    respond_to do |format|
      if @answer.save
        flash[:notice] = "Ответ удачно создан"
        format.html { redirect_to @answer.question}
        format.js   { }
        format.json { render @question, status: :created, location: @answer }
      else
        format.html { render :new }
        format.js   { }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer.question, notice: 'Ответ успешно обновлен' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @parent = @answer.question
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @parent, notice: 'Ответ удачно удален' }
      format.json { head :no_content }
    end
  end
  private

  def set_answer
    @answer = Answer.find(params[:id])
  end
  def answer_params
    params.require(:answer).permit(:title)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :admin?

  protected

  def admin?
    session[:admin]
  end

  def authorize
    unless admin?
      flash[:error] = "Доступ запрещен"
      redirect_to root_path
      false
    end
  end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :set_instruction, only: [:show, :edit, :update]
  before_action :set_answer, only: [:new, :create]
  before_action :authorize, except: [:show]

  def show

  end
  def new
    @instruction = Instruction.new
  end

  def create
    @instruction = Instruction.new(instruction_params)
    respond_to do |format|
      if @instruction.save
        if @answer.present?
          @instruction.answer = @answer
        end
        flash[:notice] = "Иструкция удачно создана"
        format.html { redirect_to @instruction}
        format.js   { }
        format.json { render :show, status: :created, location: @instruction }
      else
        format.html { render :new }
        format.js   { }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
  end

  def update
    respond_to do |format|
      if @instruction.update(instruction_params)
        format.html { redirect_to @instruction, notice: 'Инструкция успешно обновлена' }
        format.json { render :show, status: :ok, location: @instruction }
      else
        format.html { render :edit }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_answer
    @answer = Answer.find(params[:answer_id])
  end
  def set_instruction
    @instruction = Instruction.find(params[:id])
  end

  def instruction_params
    params.require(:instruction).permit(:title, :text)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :empty, :edit, :update, :destroy]
  before_action :set_answer, only: [:new, :create, :empty]
  before_action :authorize, except: [:index, :show, :empty]


  def index
    @question = Question.first
  end

  def show

  end

  def empty

  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    respond_to do |format|
      if @question.save
        if @answer.present?
          @question.answer = @answer
        end
        flash[:notice] = "Вопрос удачно создан"
        format.html { redirect_to @question}
        format.js   { }
        format.json { render :index, status: :created, location: @question }
      else
        format.html { render :new }
        format.js   { }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Вопрос успешно обновлен' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @parent = @question.answer.question
    @question.destroy
    respond_to do |format|
      format.html { redirect_to @parent, notice: 'Вопрос удачно удален' }
      format.json { head :no_content }
    end
  end
  private

    def set_answer
      @answer = Answer.find(params[:answer_id])
    end
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title)
    end



end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/_form.html.haml
= form_for :admin, url: login_path do |f|
  .field
    = f.text_field :login, :maxlength=>30
  .field
    = f.password_field :password, :maxlength=>30
  = f.button("Войти", class:"link-button")

app/views/admin/index.html.haml
.loginBox
  %h1.center-text Авторизация
  -if admin?
    %h2.text-white Вы уже авторизированы
  -else
    = render 'form'
    = link_to "На главную", root_path, class: 'link-button'
      

app/views/admin/new.html.haml
%h1 New admin

= render 'form'

= link_to 'Back', admins_path

app/views/answers/_form.html.haml
= form_for [@question, @answer] do |f|
  - if @answer.errors.any?
    #error_explanation
      %h2= "Для сохранения исправьте ошибки:"
      %ul
        - @answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title, :maxlength=>30
    = f.text_field :title
  .actions
    = f.button 'Сохранить', class: "link-button"

app/views/answers/edit.html.haml
= link_to 'Назад', questions_path, class: 'fa fa-chevron-left back-link'

%h1 Редактирование ответа на вопрос
%h4= @answer.question.title

= render 'form'

app/views/answers/new.html.haml
= link_to 'Назад', questions_path, class: 'fa fa-chevron-left back-link'


%h1 Новый ответ для вопроса
%h4= @question.title

= render 'form'

app/views/instructions/_form.html.haml
- if @answer.present?
  -@path = instruction_answer_path(@answer)
  -@method = 'post'
- else
  -@path = {}
  -@method = {}
= form_for @instruction, :url => @path, method:  @method do |f|
  - if @instruction.errors.any?
    #error_explanation
      %h2= "Для сохранения исправьте ошибки:"
      %ul
        - @instruction.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title, :maxlength=>50
    = f.text_field :title
  .field
    = f.label :text
    = f.cktext_area :text, :ckeditor => {:language => 'ru'}
  .actions
    = f.button 'Сохранить', class: "link-button"

app/views/instructions/edit.html.haml
= link_to 'Назад', instruction_path(@instruction), class: 'fa fa-chevron-left back-link'

%h1 Редактировние инструкции для ответа
- @answer = @instruction.answer
%h4 "#{@answer.title}" на вопрос "#{@answer.question.title}"

= render 'form'

app/views/instructions/new.html.haml
= link_to 'Назад', questions_path, class: 'fa fa-chevron-left back-link'


%h1 Новая инструкция для ответа
%h4 "#{@answer.title}" на вопрос "#{@answer.question.title}"

= render 'form'

app/views/instructions/show.html.haml
=link_to "Назад", @instruction.answer.question, class: 'fa fa-chevron-left back-link'
-if admin?
  .manage
    =link_to "Редактировать", edit_instruction_path(@instruction)
%h1= @instruction.title
.text
  %p= raw @instruction.text

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TheAnswerMachine
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |key, value|
      %div{:class => "alert alert-#{key}"}= value
    .center-wrapper
      = yield

app/views/questions/_form.html.haml
- if @answer.present?
  -@path = question_answer_path(@answer)
  -@method = 'post'
  -p = {:url => @path, method:  @method}
- else
  -p = {}
= form_for @question, p do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "Для сохранения исправьте ошибки:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title, :maxlength=>50
    = f.text_field :title
  .actions
    = f.button 'Сохранить', class: "link-button"

app/views/questions/_main.html.haml
- if admin?
  =link_to "Выйти", logout_path, class: 'login-link'
-else
  =link_to "Войти", login_path, class: 'login-link'
- if @question.present?
  -if @question.answer.present?
    =link_to "Назад", @question.answer.question, class: 'fa fa-chevron-left back-link'
  .question-title
    %span
      %h1= @question.title
      -if admin?
        .question-manage
          %a.edit-link.fa.fa-pencil{:href => edit_question_path(@question), title: "Редактировать"}
          =link_to "", @question, :method => :delete, data: { confirm: 'Вы уверены?' }, class: "remove-link fa fa-trash", title: "Удалить"
  .question-body
    %ul.answers
      - @question.answers.each do |answer|
        %li
          -if answer.children.present?
            =link_to answer.title, answer.children
          - else
            =link_to answer.title, empty_path(@question, answer)
          -if admin?
            .answer-manage
              %a.edit-link.fa.fa-pencil{:href => edit_answer_path(answer), title: "Редактировать"}
              =link_to "", answer, :method => :delete, data: { confirm: 'Вы уверены?' }, class: "remove-link fa fa-trash", title: "Удалить"
    - if admin?
      =link_to "Добавить ответ", new_question_answer_path(@question), class: "link-button"
-else
  =render partial: 'questions/noquestion'

app/views/questions/_noquestion.html.haml
%h1 Вопроса нет
- if admin?
  =link_to "Добавить вопрос", new_question_path, class: "link-button"

app/views/questions/_question.html.haml
%ul
  %h2.tree-head
    =link_to q.title, q
  -if q.answers.present?
    - q.answers.each do |answer|
      %li
        %span.answer-head{:title => q.title}= answer.title
      %li
        -if answer.children.present?
          -if answer.children_type == "Question"
            =render partial: 'questions/question', locals: {q: answer.children}
          -elsif answer.children_type == "Instruction"
            %h2
              =link_to answer.children.title, answer.children, class: 'instruction-head'
        -else
          %h2
            =link_to 'Вопроса или рекомендации пока нет', empty_path(q, answer), class: 'empty-head'

app/views/questions/_tree.html.haml
- if admin?
  - @first = Question.first
  .question-tree
    =render partial: 'questions/question', locals: {q: @first}

app/views/questions/edit.html.haml
= link_to 'Назад', questions_path, class: 'fa fa-chevron-left back-link'

%h1 Редактирование вопроса

= render 'form'

app/views/questions/empty.html.haml
=link_to "Назад", @answer.question, class: 'fa fa-chevron-left back-link'
%h1 Вопроса нет
- if admin?
  =link_to "Добавить вопрос", new_fat_question_path(@answer), class: "link-button"
  =link_to "Добавить инструкцию", new_instruction_path(@answer), class: "link-button"

app/views/questions/index.html.haml
=render partial: 'questions/main'
=render partial: 'questions/tree'

app/views/questions/new.html.haml
= link_to 'Назад', questions_path, class: 'fa fa-chevron-left back-link'

%h1 Новый вопрос

= render 'form'

app/views/questions/show.html.haml
=render partial: 'questions/main'
=render partial: 'questions/tree'